baseURL = "https://antzucaro.com/"
languageCode = "en-us"
theme = ["overrides", "hugo-coder"]
title = "Random Thoughts and Geekery"

[Menus]
  main = [
      {Name = "photography", URL = "/categories/photography"},
      {Name = "archive", URL = "/posts/"},
      {Name = "about", URL = "/about/"},
  ]

[markup.goldmark.renderer]
unsafe = true

[params]
author = "Ant Zucaro"
info = "Coder, Photographer"
description = "by Ant Zucaro"
avatarurl = "static/img/avatar_real.jpg"
hideColorSchemeToggle=true
copyright = "Ant Zucaro"
since = 2010
paginate = 20
customJS = ["js/lazysizes.min.js"]

[[params.social]]
name = "Gitlab"
icon = "fa fa-gitlab fa-2x"
weight = 1
url = "https://www.gitlab.com/antibody"

[[params.social]]
name = "GitHub"
icon = "fa fa-github fa-2x"
weight = 2
url = "https://www.github.com/antzucaro"

[[params.social]]
name = "Instagram"
icon = "fa fa-instagram fa-2x"
weight = 3
url = "https://www.instagram.com/dfdashh"
